### PR TITLE
Theme: Update to crate-docs-theme==0.34.0.dev6

### PR DESCRIPTION
**Pull request by amotl**
## About
This RTD build gives you the chance to preview and review the documentation, using a pre-release of the modernized crate-docs-theme, based on sphinx-basic-ng/Furo.

> [!NOTE]
> **Also increases toctree maxdepth to 4.** That may be good, or not, or it doesn't matter at all. Before, it was 2. See https://github.com/crate/crate-docs-theme/pull/515.

## Preview
https://crate-cloud--79.org.readthedocs.build/en/79/

## Thoughts
- It doesn't look too bad. Thanks for your fixes, @msbt!

- If you agree, and don't object a slight anomaly in appearance, because other projects are not using the modernized theme yet, you are free to merge it at your disposal.

- If you can spot and flaws or other more serious regressions, or just little ones, please let us know about them!

## References
- https://github.com/crate/crate-docs-theme/pull/390
- https://github.com/crate/crate-docs-theme/pull/510

/cc @surister, @simonprickett, @kneth

### CODE REVIEW

**Review by msbt — APPROVED** [review]
lets go

**Comment by amotl** [comment]
> lets go

^^ @proddata can decide if he wants to merge it, or not. If yes, please do on your own behalf. Thanks!

**Comment by amotl** [comment]
> **Also increases toctree maxdepth to 4**. Before, it was 2.

It certainly makes a difference, for example here.

Previous: https://cratedb.com/docs/cloud/en/latest/howtos/create-org.html
Future? https://crate-cloud--79.org.readthedocs.build/en/79/howtos/create-org.html

image

**Comment by amotl** [comment]
Hi again. It looks like both `<li>`/`<a>` woes, and [flaws with tables](https://github.com/crate/crate-docs-theme/pull/510#issuecomment-2260354540), have been [resolved now](https://github.com/crate/crate-docs-theme/pull/510#issuecomment-2269472025).

Can you spot any other problems?

**Review by proddata — APPROVED** [review]

**Comment by amotl** [comment]
Thanks for merging!

**Comment by proddata** [comment]
> Thanks for merging!

I just followed your orders :D

**Pull request merged**
