### PR TITLE
Update Edge Introduction pictures

### PR DESCRIPTION
**Pull request by matkuliak**
## Summary of the changes / Why this is an improvement
- updated Edge Intro pictures
- removed `:scale: 50%` 

## Checklist

 - [x] Link to issue this PR refers to (if applicable): https://github.com/crate/cloud-docs/issues/43
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by amotl** [comment]
Hi. Was it just some conversion using oxipng, or are those real updates? If the latter is the case, I would like to suggest to switch to a better style/paradigm of having screenshots in the documentation.

https://thisisimportant.net/posts/screenshots-in-documentation/
-- via: https://news.ycombinator.com/item?id=38639629

My proposal is to [Use simplified screenshots](https://thisisimportant.net/posts/screenshots-in-documentation/#use-simplified-screenshots) exclusively.

**Review by amotl — APPROVED** [review]
Acknowledging. Please still consider our suggestion about Simplified Screenshots. It might be a dedicated round of updates, and we do not want to block you from merging.

**Comment by matkuliak** [comment]
Hi. I see where you're coming from. 
Screenshots are highly debatable topic, I agree that we could do them better. For one, we could (should?) do less of them. I am guilty of this myself, it's easy to rely on them.

I added "screenshot overhaul" to my backlog and will consider your suggestion. Obscuring parts sound like a good idea to me.

**Comment by amotl** [comment]
Thanks!

> Obscuring parts sound like a good idea to me.

Not only obscuring, but also cropping down to the element of interest.

**Pull request merged**
