### PR TITLE
improve screenshots

### PR DESCRIPTION
**Pull request by mechanomi**

### CODE REVIEW

**Comment by MarkusH** [comment]
The `docs/overview.png` image shows a CrateDB version 2.x. That should probably better be a 3.1.x or so?

**Comment by mechanomi** [comment]
@MarkusH I'm just documenting what's running in production atm via the login you gave me. is this not the correct version in that context?

**Comment by MarkusH** [comment]
No no, it's the version that's running, but afaict it's a legacy cluster and CrateDB Cloud supports only CrateDB >= 3.0 or 3.1.

**Comment by lukas-bernert** [comment]
@MarkusH valid point. Although, I don't see the cluster version as critical. To me the PR looks good.

**Pull request merged**
